export type FormValues = {
	id: string;
	firstName: string;
	lastName: string;
	email: string;
	DOB: string;
	phone: string;
	gender: "male" | "female";
	countryCode?: string;
	currentCity: string;
	neighborhood?: string;
	stateOfOrigin: string;
	profession: string;
	business?: string;
	brandName?: string;
	company: string;
	bio?: string;
	password: string;
	confirmPassword: string;
	isTermAndConditionAccepted: boolean;
};
